### ISSUE TITLE
jjtree/c++: stunning generated code that compiles ok on VS2017 and fails with g++ 7.5.0

### ISSUE THREAD

**Issue by zosrothko** [javacc/codegenerator#75]
Hello

This generated code below from the grammar located in this project: javacc-8.0\codegen\cpp\grammars\ecma\src\main\jjtree\EcmaScript.jjt

```
[INFO] OUTPUT>In file included from ../../target/generated-sources/cpp/EcmaScriptTokenManager.h:10:0,
[INFO] OUTPUT>                 from ../../target/generated-sources/cpp/EcmaScriptTokenManager.cc:2:
[ERROR] OUTPUT>../../target/generated-sources/cpp/EcmaScriptConstants.h:298:9: error: narrowing conversion of ‘160’ from ‘int’ to ‘JJChar {aka char}’ inside { } [-Wnarrowing]
[INFO] OUTPUT> {0xa0, 0};
[INFO] OUTPUT>         ^
[ERROR] OUTPUT>../../target/generated-sources/cpp/EcmaScriptConstants.h:308:11: error: narrowing conversion of ‘8232’ from ‘int’ to ‘JJChar {aka char}’ inside { } [-Wnarrowing]
[INFO] OUTPUT> {0x2028, 0};
[INFO] OUTPUT>           ^
[ERROR] OUTPUT>../../target/generated-sources/cpp/EcmaScriptConstants.h:310:11: error: narrowing conversion of ‘8233’ from ‘int’ to ‘JJChar {aka char}’ inside { } [-Wnarrowing]
[INFO] OUTPUT> {0x2029, 0};
[INFO] OUTPUT>           ^

```

there is also this warning
```
[INFO] OUTPUT>../../target/generated-sources/cpp/EcmaScriptTokenManager.cc:316:2184: warning: integer constant is so large that it is unsigned          [INFO] OUTPUT> {304LL, 1LL, 287948969894477824LL, 1LL, 576460745995190270LL, 1LL, 297241973452963840LL, 1LL, -36028797027352577LL, 4LL, -1LL, 1LL, 4503586742468607LL, 1LL, -65536LL, 1LL, -432556670460100609LL, 1LL, 70501888360451LL, 1LL, -1LL, 1LL, 288230406216515583LL, 1LL, -17179879616LL, 1LL, 4503599577006079LL, 2LL, -1LL, 1LL, -3973LL, 1LL, 234187180623206815LL, 1LL, -562949953421312LL, 1LL, -8547991553LL, 1LL, -4899916411759099649LL, 1LL, 1979120929931286LL, 1LL, 576460743713488896LL, 1LL, -277081220972545LL, 1LL, -1LL, 1LL, 2305629702346244095LL, 1LL, -246290604687360LL, 1LL, 2047LL, 1LL, 562949953421311LL, 5LL, 0LL, 1LL, -864691128455135250LL, 1LL, 281268803551231LL, 1LL, -881018876128026642LL, 1LL, 1125692414638495LL, 1LL, -3211631683292264468LL, 1LL, 9006925953907079LL, 1LL, -869759877059465234LL, 1LL, 281204393851839LL, 1LL, -878767076314341394LL, 1LL, 281215949093263LL, 1LL, -4341532606274353172LL, 1LL, 280925229301191LL, 1LL, -4327961440926441490LL, 1LL, 281212990012895LL, 1LL, -4327961440926441492LL, 1LL, 281214063754719LL, 1LL, -4323457841299070996LL, 1LL, 281212992110031LL, 1LL, 3457638613854978028LL, 1LL, 3377704004977791LL, 1LL, 576460752303423486LL, 1LL, 67076095LL, 1LL, -288251614782806634LL, 1LL, 872365919LL, 1LL, -4422530440275951615LL, 1LL, -554153860399105LL, 1LL, 2305843009196855263LL, 1LL, 64LL, 1LL, 272457864671395839LL, 1LL, 67044351LL, 1LL, -4294967296LL, 1LL, 36028797018898495LL, 1LL, -1LL, 1LL, -2080374785LL, 1LL, -1065151889409LL, 1LL, 288230376151711743LL, 1LL, -129LL, 1LL, -3263218305LL, 1LL, 9168625153884503423LL, 1LL, -140737496776899LL, 1LL, -2160230401LL, 1LL, 1123701017804671LL, 1LL, -4294967296LL, 1LL, 9007199254740991LL, 1LL, -2LL, 8LL, -1LL, 1LL, 36028797018963967LL, 1LL, -4160749570LL, 1LL, 8796093022207LL, 2LL, 0LL, 1LL, -1LL, 1LL, 4393752592383LL, 1LL, -4227923968LL, 1LL, 72057594037927935LL, 1LL, 4398046511103LL, 1LL, 0LL, 1LL, 142723721751166976LL, 1LL, 0LL, 1LL, -281474976710656LL, 1LL, 769LL, 1L
```

One can reproduce this issue on Linux with: 
```
cd javacc-8.0/codegen/cpp/grammars/ecma
mvn clean install
```

Look at the `build.log` file.

**Comment by zosrothko** [comment]
Missing invoker.properties in the maven project `ecma`. Also fix missing <nodeDirectory> in the profile jjt8w
